services:
    db:
        image: postgres:15-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_PASSWORD: masterkey
            POSTGRES_USER: pgadm
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            - "DATABASE_ENGINE=django.db.backends.postgresql"
            - "DATABASE_URL=postgresql://pgadm:masterkey@db:5432/pgadm"
            - "DJANGO_SECRET_KEY=a1b2c3d4f5e6"
            - "DJANGO_DEBUG=1"

        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
        - db
volumes:
    postgres_data:
